export const FETCH_EVENTS_REQUEST = "@@auth/FETCH_EVENTS_REQUEST";
export const FETCH_EVENTS_SUCCESS = "@@auth/FETCH_EVENTS_SUCCESS";
export const FETCH_EVENTS_ERROR = "@@auth/FETCH_EVENTS_ERROR";
export const FETCH_TAGS_REQUEST = "@@auth/FETCH_TAGS_REQUEST";
export const FETCH_TAGS_SUCCESS = "@@auth/FETCH_TAGS_SUCCESS";
export const FETCH_TAGS_ERROR = "@@auth/FETCH_TAGS_ERROR";
export const SORT_EVENTS = "@@auth/SORT_EVENTS";
